<img src="https://cmse.msu.edu/_assets/images/about/image001.png"
     alt="CMSE Logo"
     align="right" 
     height="400" 
     width="400" />
# <font color=18453B>CMSE 801 - Day 19</font>
## Exploring the properties of an agent-based model for modeling forest fires
### March 24, 2026

## General Course Announcements

* Homework 4 is available and due **April 4 by 11:59pm**.
* Make sure you're working on your project!
    * Class cancelled on April 2
    * You'll be presenting project drafts during the Day 22 class period (**April 7**).

## Questions/comments from Day 19 PCA

* Some folks ran into issues getting the plurality voting functions coded up
    - This requires some careful array indexing and thoughtful conditional statements.
* Other folks were able to get the plurality stuff working, but ran into issues with calculating the fraction of last place votes.


## Let's generate our ballots!

In [3]:
# Generating the data table
import numpy as np
import random
ballot_list=[]
for i in range(29):
    ballot_list.append(['a','b','c'])
for i in range(1):
    ballot_list.append(['a','c','b'])
for i in range(23):
    ballot_list.append(['b','a','c'])
for i in range(3):
    ballot_list.append(['b','c','a'])
for i in range(26):
    ballot_list.append(['c','b','a'])
for i in range(18):
    ballot_list.append(['c','a','b'])
# make the data into a 2D numpy array    
ballot_list=np.array(ballot_list)
# use np.random.shuffle to mix up the order just for fun and authenticity
np.random.shuffle(ballot_list)
print(ballot_list[:5])

[['c' 'b' 'a']
 ['c' 'b' 'a']
 ['a' 'b' 'c']
 ['a' 'b' 'c']
 ['a' 'b' 'c']]


# Let's take a look at couple possible solutions for the plurality voting

In [4]:
## Option 1, go through every ballot with a loop and see who was selected
def plurality_1(bl):
    candidate_count= np.zeros(3)
    for i in range(len(bl)):
        if bl[i,0] == 'a':
            candidate_count[0]+=1
        elif bl[i,0]=='b':
            candidate_count[1]+=1
        else:
            candidate_count[2]+=1
    print("First choice votes for each candidate:\n",candidate_count)
    return np.argmax(candidate_count)

In [5]:
print("Which candidate won?",plurality_1(ballot_list))

First choice votes for each candidate:
 [30. 26. 44.]
Which candidate won? 2


In [6]:
## Option 2: create an array of all the first choice votes, then make a mask
def plurality_2(bl):
    first_choice_votes=np.array(bl[:,0])
    candidate_count= np.zeros(3)
    candidate_count[0]=len(first_choice_votes[first_choice_votes == 'a'])
    candidate_count[1]=len(first_choice_votes[first_choice_votes == 'b'])
    candidate_count[2]=len(first_choice_votes[first_choice_votes == 'c'])
    print("First choice votes for each candidate:\n",candidate_count)
    return np.argmax(candidate_count)

In [7]:
print("Which candidate won?",plurality_2(ballot_list))

First choice votes for each candidate:
 [30. 26. 44.]
Which candidate won? 2


## What if we want to know the fraction of people that chose a candidate _last_?
    

In [8]:
def lastplace(bl, c):
    # We use array indexing to get the last place votes
    # Then we create mask for those values that match the candidate
    # We sum that mask because "True" is equal to "1"
    # and then divide the result by the total number of ballots
    frac_last = (bl[:,-1] == c).sum() / len(ballot_list)
    return frac_last

print(lastplace(ballot_list, 'a'))
print(lastplace(ballot_list, 'b'))
print(lastplace(ballot_list, 'c'))

0.29
0.19
0.52


### But we could have also used our previous function!

In [9]:
def plurality_last_fraction(bl):
    last_choice_votes=np.array(bl[:,-1])
    candidate_count= np.zeros(3)
    candidate_count[0]=len(last_choice_votes[last_choice_votes == 'a'])
    candidate_count[1]=len(last_choice_votes[last_choice_votes == 'b'])
    candidate_count[2]=len(last_choice_votes[last_choice_votes == 'c'])
    print("Last choice votes for each candidate:\n",candidate_count)
    return candidate_count[0]/len(bl), candidate_count[1]/len(bl), candidate_count[2]/len(bl)

In [10]:
print("Last choice fractions?",plurality_last_fraction(ballot_list))

Last choice votes for each candidate:
 [29. 19. 52.]
Last choice fractions? (np.float64(0.29), np.float64(0.19), np.float64(0.52))


### Using `np.where` to find values locations and to mask and filter data

In [11]:
my_array=np.array([1,2,3,5,1])
print("Result of where:",np.where(my_array==2))
print("Results of using where to mask data:",my_array[np.where(my_array==2)])

Result of where: (array([1]),)
Results of using where to mask data: [2]


### Let's explore this with the ballot list, which is 2D

In [12]:
candidate_c = np.where(ballot_list == 'c')
print("Result of where:\n",candidate_c)

Result of where:
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]), array([0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0,
       0, 2, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 0, 1, 2,
       0, 0, 2, 0, 2, 0, 2, 1, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 1, 0, 2, 0,
       2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2,
       2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 2, 0]))


In [13]:
ballot_list[candidate_c]

array(['c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c',
       'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c',
       'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c',
       'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c',
       'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c',
       'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c',
       'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c',
       'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c'], dtype='<U1')

## Goals for today
* Continue manipulating 2D NumPy arrays to store data as well as to build and run models
* Finish off the forest fire model.
    * Functions from last time are provided
    * You need to build a function to analyze the state of the board
    * Read, comment, and understand some code that runs one simulation
    * You need to complete a some that runs many simulations for a series of starting tree fractions
* The work you do today will allow you to explore the properties of the model you built
* You'll also be able to explore if changing the initial state of the board has a significant impact on the results

## Looking forward - Day 20 PCA: An introduction to "Object-oriented programming" (OOP) in Python

* You'll explore the concept of "object-oriented programming"
* You'll think about how you've already leveraged this programming paradigm in how you've been using Python
* You'll be introduce to Python "classes" which is what Python calls "objects"