# CMSE 801 - Day 12
## Agent-based Modeling

### Oct 12, 2022

## General Course Announcements

* The midterm exam is next week!
* Homework #3 will be released today

## Questions/comments from Day 12 PCA 

* I'm confused as to why we loop over the rows and the columns in 2D arrays? Would just one or the other go over every index?
* need more help with indexing rows and column
* For the for loop, we take the i and the j values like so: for i in range(zeros.shape[0]): So is the [0] going to always by the rows? And the [1] is the columns? is is the i and j that determines that? Also explain the difference between the i and j perhaps?
* what is x_indexes[myarray == 1] doing
* I just wrote a easier code to finish the task than the instruction, can I use it instead of following the instruction?

* If the random funciton is "pseudo-random" based on the seed, are there some seeds that can get "non-random" numbers? Like we can get 10 same numbers at the beginning.
* I did not know how to do the last part.
* I think I need more examples of the agent-based models to better understand them!
* I need to work with a few more ABMs to fully grasp them, but I believe that will be coming in the next few classes
* I feel like this class took a big step with out me. 
* Thank you! I feel like I am learning more than I have in years / Nothing at the moment, thanks!

In [1]:
import numpy as np

In [34]:
np.random.seed(123)
for i in range(5):
    print(np.random.random())

0.6964691855978616
0.28613933495037946
0.2268514535642031
0.5513147690828912
0.7194689697855631


In [40]:
for i in range(5):
    print(np.random.random())

0.09210493994507518
0.43370117267952824
0.4308627633296438
0.4936850976503062
0.425830290295828


In [41]:
x_range = np.linspace(0, 1, 3) 
y_range = np.linspace(0, 0.5, 5) 
x_indexes, y_indexes = np.meshgrid(x_range, y_range) 
print(x_range)
print(y_range)
print(x_indexes)
print(y_indexes)

[0.  0.5 1. ]
[0.    0.125 0.25  0.375 0.5  ]
[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0.    0.    0.   ]
 [0.125 0.125 0.125]
 [0.25  0.25  0.25 ]
 [0.375 0.375 0.375]
 [0.5   0.5   0.5  ]]


In [42]:
array = np.random.rand(5,3)
print(array)
print('---')
print(x_indexes)
print('---')
print(x_indexes[array>0.3])

[[0.31226122 0.42635131 0.89338916]
 [0.94416002 0.50183668 0.62395295]
 [0.1156184  0.31728548 0.41482621]
 [0.86630916 0.25045537 0.48303426]
 [0.98555979 0.51948512 0.61289453]]
---
[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]
---
[0.  0.5 1.  0.  0.5 1.  0.5 1.  0.  1.  0.  0.5 1. ]


In [43]:
def create_forest(N, ftreestart):
    
    # Initialize a 2D array full of zeros using np.zeros
    forest = np.zeros((N,N))

    # Loop through the 2D array to initialize the trees    
    for i in range(N):
        for j in range(N):
            if np.random.random()< ftreestart:
                forest[i,j] = 1
    
    forest[:,0] = 2
    
    return forest

In [44]:
forest_array = create_forest(5, .3)
print(forest_array)

[[2. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [2. 0. 1. 1. 0.]
 [2. 0. 0. 0. 1.]]
