# CMSE 801 - Day 11
## NumPy Arrays

### October 10, 2022

## General Course Announcements

* How the Homework assignment 2 is going? 
* Midterm will be on Wednesday Oct 19 during the class
* The details of the semester project have been released

## Questions/comments from Day 11 PCA

* What is "cmap" when viewing the RGB portions of our jpeg? The '?' function says that cmap is not necessary for RGB(A) data, but if I take it out the result is different when I run the code. Is the type of RGB we have not RGB(A)? How can we tell what to put in the "cmap" value?
* loading images are still kind of confusing to me.
* Everything about loading images and interpreting arrays from them. I'm very confused.
* Could you introduce more of how to use colon in class? Thanks.

* Explanation from the beginning of how to load images and how to interpret arrays from them. The code supplied was incredibly confusing to me. 
* If we can load picture and edit it in python, so maybe we can also apply it on other things like music? 
* OMG, I just find a new method to edit the picture in python without putting it into Photoshop, especially the colors which have confused me for a long time. It is really inspiring. Thank you!
* The overall numpy material was good and it's now starting to click (also thank you for including the old videos again - great refresher!). 
* I liked masking!

In [1]:
import numpy as np

x = np.random.rand(5,5)
print(x)

[[0.62370071 0.02483425 0.11740013 0.19633929 0.16491161]
 [0.22838453 0.82312016 0.02097911 0.62918149 0.21533057]
 [0.172541   0.58090661 0.50018304 0.58287403 0.61130619]
 [0.97720108 0.44576396 0.04613512 0.83322873 0.06018914]
 [0.6276781  0.78665777 0.15637946 0.86657525 0.99948223]]


In [2]:
# first column
print(x[:,0])
# second row from component 2 to the end
print(x[1,1:])
# second row from component 2 to 3
print(x[1,1:3])
print(x[1:3,1:3])

[0.62370071 0.22838453 0.172541   0.97720108 0.6276781 ]
[0.82312016 0.02097911 0.62918149 0.21533057]
[0.82312016 0.02097911]
[[0.82312016 0.02097911]
 [0.58090661 0.50018304]]


In [3]:
# copy 
y = x.copy()
x[0] = 2.0
print(y)
print(x)

[[0.62370071 0.02483425 0.11740013 0.19633929 0.16491161]
 [0.22838453 0.82312016 0.02097911 0.62918149 0.21533057]
 [0.172541   0.58090661 0.50018304 0.58287403 0.61130619]
 [0.97720108 0.44576396 0.04613512 0.83322873 0.06018914]
 [0.6276781  0.78665777 0.15637946 0.86657525 0.99948223]]
[[2.         2.         2.         2.         2.        ]
 [0.22838453 0.82312016 0.02097911 0.62918149 0.21533057]
 [0.172541   0.58090661 0.50018304 0.58287403 0.61130619]
 [0.97720108 0.44576396 0.04613512 0.83322873 0.06018914]
 [0.6276781  0.78665777 0.15637946 0.86657525 0.99948223]]


In [4]:
a = 100*x[1,1:]
b = a.round()
print(b)
print(type(b[0]))
b = b.astype(int) 
print(b)
print(type(b[0]))

[82.  2. 63. 22.]
<class 'numpy.float64'>
[82  2 63 22]
<class 'numpy.int64'>


In [5]:
mask = x >= 0.5
mask1 = (x>=0.5) & (x<0.75)
print(x)
print(mask)
print(mask1)

[[2.         2.         2.         2.         2.        ]
 [0.22838453 0.82312016 0.02097911 0.62918149 0.21533057]
 [0.172541   0.58090661 0.50018304 0.58287403 0.61130619]
 [0.97720108 0.44576396 0.04613512 0.83322873 0.06018914]
 [0.6276781  0.78665777 0.15637946 0.86657525 0.99948223]]
[[ True  True  True  True  True]
 [False  True False  True False]
 [False  True  True  True  True]
 [ True False False  True False]
 [ True  True False  True  True]]
[[False False False False False]
 [False False False  True False]
 [False  True  True  True  True]
 [False False False False False]
 [ True False False False False]]


In [6]:
y = x[mask]
print(x.shape)
print(y)
print(y.shape)

(5, 5)
[2.         2.         2.         2.         2.         0.82312016
 0.62918149 0.58090661 0.50018304 0.58287403 0.61130619 0.97720108
 0.83322873 0.6276781  0.78665777 0.86657525 0.99948223]
(17,)


In [7]:
print(x)
x[mask] = 1000
print(x)

[[2.         2.         2.         2.         2.        ]
 [0.22838453 0.82312016 0.02097911 0.62918149 0.21533057]
 [0.172541   0.58090661 0.50018304 0.58287403 0.61130619]
 [0.97720108 0.44576396 0.04613512 0.83322873 0.06018914]
 [0.6276781  0.78665777 0.15637946 0.86657525 0.99948223]]
[[1.00000000e+03 1.00000000e+03 1.00000000e+03 1.00000000e+03
  1.00000000e+03]
 [2.28384525e-01 1.00000000e+03 2.09791140e-02 1.00000000e+03
  2.15330574e-01]
 [1.72540998e-01 1.00000000e+03 1.00000000e+03 1.00000000e+03
  1.00000000e+03]
 [1.00000000e+03 4.45763962e-01 4.61351246e-02 1.00000000e+03
  6.01891403e-02]
 [1.00000000e+03 1.00000000e+03 1.56379456e-01 1.00000000e+03
  1.00000000e+03]]


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
picture = Image.open("example.jpeg")
plt.imshow(picture)
plt.axis('off')

In [ ]:
print(type(picture))

In [ ]:
img_array = np.asarray(picture)
print(type(img_array))
print(img_array.shape)
print(img_array[:,:,0])

In [ ]:
red_array, green_array, blue_array = img_array[:,:,0], img_array[:,:,1], img_array[:,:,2]
plt.imshow(red_array, cmap = "Reds_r")

In [ ]:
plt.imshow(red_array, cmap = "Reds")

In [ ]:
plt.imshow(red_array, cmap = "gray")